/* eslint-disable @next/next/no-img-element */
import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import { motion } from 'framer-motion';
import request from 'graphql-request';
import {
	ArrowRightIcon,
	BookOpenIcon,
	BracketsIcon,
	BriefcaseIcon,
	CalendarIcon,
	GraduationCapIcon,
	LightbulbIcon,
	MapPinIcon,
	StarIcon,
} from 'lucide-react';
import { GetStaticProps } from 'next';
import Link from 'next/link';
import { AppProvider } from '../components/contexts/appContext';
import Chatbot from '../components/features/chatbot/Chatbot';
import ModernHeader from '../components/features/navigation/modern-header';
import { Container } from '../components/shared/container';
import { Footer } from '../components/shared/footer';
import { SEOHead } from '../components/shared/seo-head';
import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from '../components/ui/accordion';
import { Badge, Button } from '../components/ui';
import { generatePersonStructuredData } from '../lib/structured-data';
import {
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT || 'https://gql.hashnode.com/';

type Props = {
	publication: PublicationFragment;
};

/**
 * About page component displaying professional information and experience
 * @param publication - Publication data from Hashnode
 * @returns JSX element for the about page
 */
export default function About({ publication }: Props) {
	// Import skills from centralized data source to avoid duplication
	let skills: Record<string, string[]> = {};
	
	try {
		const { skills: skillsData } = require('../../data/skills');
		
		// Validate skills data structure
		if (Array.isArray(skillsData)) {
			// Group skills by category for display with proper error handling
			skills = skillsData.reduce((acc: Record<string, string[]>, skill: any) => {
				if (skill && typeof skill === 'object' && skill.category && skill.name) {
					if (!acc[skill.category]) {
						acc[skill.category] = [];
					}
					acc[skill.category].push(skill.name);
				}
				return acc;
			}, {});
		} else {
			console.warn('Skills data is not in expected array format');
		}
	} catch (error) {
		console.error('Error loading skills data:', error);
		// Fallback to empty skills object to prevent page crash
		skills = {};
	}

	const experience = [
		{
			title: 'Senior Front-End Developer',
			company: 'IntraWeb Technology',
			period: '2020 - Present',
			location: 'Montville, NJ',
			description: 'Lead front-end for company site and client projects; incubated SynaplyAI.',
			achievements: [
				'Built the IntraWeb Technologies website with Next.js, React, TypeScript, and Tailwind CSS; shipped an accessible, SEO-optimized presence.',
				'Delivered custom WordPress and Shopify builds emphasizing mobile performance and SEO for clients including KAL Design.',
				'Scoped requirements, owned timelines, and served as primary client liaison to ensure quality delivery and satisfaction.',
				'Incubated SynaplyAI (multi-tenant AI content collaboration) with front-end architecture, OpenAI integrations, real-time collab editing, and adaptive AI content generation.',
			],
		},
		{
			title: 'Full-Stack Developer',
			company: 'ColorStreet',
			period: '2024',
			location: 'Totowa, NJ',
			description: 'Contributed to e-commerce platform quality and integrations.',
			achievements: [
				'Implemented automated UI testing with Playwright, improving reliability across releases.',
				'Integrated and validated Nest.js APIs; ensured stable data flow and interface alignment.',
				'Partnered with QA, design, and product to support sprint delivery and UI improvements.',
			],
		},
		{
			title: 'Senior Front-End Developer',
			company: 'Executive Five Star',
			period: '2016 - 2020',
			location: 'Montville, NJ',
			description: "Owned front-end for the company's car service site and online booking.",
			achievements: [
				'Developed and maintained the primary WordPress site with improved usability and mobile responsiveness.',
				'Integrated Limo Anywhere API for real-time reservations and back-office sync.',
				'Streamlined dispatch workflows by connecting booking front-end to internal systems.',
			],
		},
		{
			title: 'Front-End Developer',
			company: 'Robert Half Technology',
			period: '2013 - 2016',
			location: 'Parsippany, NJ',
			description: 'Built enterprise UIs and internal tooling in JavaScript ecosystems.',
			achievements: [
				'Developed UIs for internal financial platforms using JavaScript, jQuery, and Bootstrap to improve reporting workflows.',
				'Built interactive presentation tools for pharmaceutical clients using Veeva CRM and HTML5.',
				'Delivered front-end features aligned with enterprise UX guidelines in Agile cycles.',
				'Led multiple internal WordPress projects and mentored junior developers on front-end best practices.',
			],
		},
		{
			title: 'Web Developer (Contract)',
			company: 'Level-Nine Creative',
			period: '2009 - 2013',
			location: 'Merritt Island, FL',
			description: 'Delivered custom WordPress sites for small businesses and agencies.',
			achievements: [
				'Designed and developed custom websites using WordPress, PHP, JavaScript, and CSS.',
				'Built reusable UI components for responsive, cross-browser performance.',
				'Customized themes/plugins to support marketing workflows and SEO.',
			],
		},
		{
			title: 'Web Development Program Director',
			company: 'Anthem Institute',
			period: '2005 - 2009',
			location: 'Parsippany, NJ',
			description: 'Led curriculum and instruction across multiple campuses.',
			achievements: [
				'Taught HTML, CSS, JavaScript, PHP, and MySQL; built industry-ready skills.',
				'Managed a team of 8 instructors across 4 campuses; ensured curriculum alignment.',
				'Oversaw accreditation compliance; partnered with Pearson VUE for certification programs.',
			],
		},
	];

	const education = [
		{
			degree: 'Web & Graphic Design',
			school: 'The Chubb Institute',
			period: '2004',
			location: 'New Jersey',
			description: 'Diploma in Web & Graphic Design',
		},
	];

	const certifications = [
		{
			name: '15+ Years Experience',
			issuer: 'Web Development',
			year: '2005-2025',
		},
	];

	return (
		<AppProvider publication={publication}>
			<SEOHead
				title={`About - ${publication.displayTitle || publication.title}`}
				description="Learn more about John Schibelli, Senior Front-End Developer specializing in React, Next.js, TypeScript, and AI-driven development."
				keywords={[
					'John Schibelli',
					'Front-End Developer',
					'React Developer',
					'Next.js Developer',
					'TypeScript Developer',
					'Web Development',
					'Professional Experience',
					'Skills',
					'Portfolio',
				]}
				canonical="/about"
				ogImage={getAutogeneratedPublicationOG(publication)}
				ogType="profile"
				structuredData={generatePersonStructuredData({
					name: 'John Schibelli',
					description: 'Senior Front-End Developer with 15+ years of experience building scalable, high-performance web applications.',
					url: 'https://johnschibelli.com',
					jobTitle: 'Senior Front-End Developer',
					knowsAbout: [
						'JavaScript (ES6+)',
						'TypeScript',
						'React',
						'Next.js',
						'Node.js',
						'HTML5',
						'CSS3',
						'Tailwind CSS',
						'GraphQL',
						'REST APIs',
						'Web Accessibility',
						'SEO Optimization',
						'Performance Optimization',
						'UI/UX Design',
						'Testing',
						'DevOps',
						'Cloud Computing',
					],
					alumniOf: [
						{
							name: 'The Chubb Institute',
						},
					],
					hasCredential: [
						{
							name: '15+ Years Experience',
							credentialCategory: 'Work Experience',
							recognizedBy: {
								name: 'Web Development Industry',
							},
						},
					],
					sameAs: [
						'https://linkedin.com/in/johnschibelli',
						'https://github.com/johnschibelli',
						'https://twitter.com/johnschibelli',
					],
				})}
			/>

			<ModernHeader publication={publication} />

			<main className="min-h-screen bg-background">
				{/* Hero Section */}
				<section
					className="relative min-h-[400px] overflow-hidden bg-muted py-12 md:py-16"
					style={{
						backgroundImage: 'url(/assets/hero/hero-bg.png)',
						backgroundSize: 'cover',
						backgroundPosition: 'center',
						backgroundRepeat: 'no-repeat',
					}}
				>
					{/* Background Overlay */}
					<div className="absolute inset-0 z-0 bg-muted/70"></div>
					{/* Content Overlay */}
					<div className="relative z-10">
						<Container className="px-4">
							<motion.div
								initial={{ opacity: 0, y: 20 }}
								animate={{ opacity: 1, y: 0 }}
								transition={{ duration: 0.8, ease: 'easeOut' }}
								className="mx-auto max-w-5xl"
							>
								<div className="grid grid-cols-1 items-center gap-8 lg:grid-cols-3 lg:gap-10">
									{/* Profile Image */}
									<div className="flex justify-center lg:col-span-1">
										<div className="relative">
											<div className="h-48 w-48 overflow-hidden rounded-full bg-gradient-to-br from-stone-200 to-stone-300 md:h-56 md:w-56 lg:h-52 lg:w-52 dark:from-stone-700 dark:to-stone-600">
												<img
													src="/assets/hero/profile.png"
													alt="John Schibelli - Senior Frontend Developer"
													className="h-full w-full object-cover"
												/>
											</div>
											<div className="absolute -bottom-1 -right-1 flex h-12 w-12 items-center justify-center rounded-full bg-stone-900 md:h-14 md:w-14 dark:bg-stone-100">
												<BracketsIcon className="h-6 w-6 text-white md:h-7 md:w-7 dark:text-stone-900" />
											</div>
										</div>
									</div>

									{/* Hero Content */}
									<div className="text-center lg:col-span-2 lg:text-left">
										<h1 className="mb-4 text-4xl font-bold text-stone-900 md:text-5xl lg:text-6xl dark:text-stone-100">
											John Schibelli
										</h1>
										<p className="mb-4 text-xl text-stone-600 md:text-2xl lg:text-3xl dark:text-stone-400">
											Senior Front-End Developer
										</p>
										<p className="mb-6 text-base leading-relaxed text-stone-600 md:text-lg dark:text-stone-400">
											Senior Front-End Developer with 15+ years of experience building scalable,
											high-performance web apps and company websites. Skilled in React, Next.js,
											TypeScript, and Tailwind CSS with a strong focus on accessibility, SEO, and
											client success.
										</p>

										<div className="mb-6 flex flex-wrap justify-center gap-3 text-sm text-stone-500 md:gap-4 lg:justify-start dark:text-stone-400">
											<div className="flex items-center gap-2">
												<MapPinIcon className="h-4 w-4" />
												<span>Towaco, NJ</span>
											</div>
											<div className="flex items-center gap-2">
												<BriefcaseIcon className="h-4 w-4" />
												<span>15+ Years Experience</span>
											</div>
											<div className="flex items-center gap-2">
												<CalendarIcon className="h-4 w-4" />
												<span>Available for Projects</span>
											</div>
										</div>

										<div className="flex flex-col justify-center gap-3 sm:flex-row lg:justify-start">
											<Button
												size="lg"
												asChild
											>
												<Link href="/contact">
													Get In Touch
													<ArrowRightIcon className="ml-2 h-4 w-4" />
												</Link>
											</Button>
											<Button
												size="lg"
												variant="outline"
												asChild
											>
												<Link href="/projects">View My Projects</Link>
											</Button>
										</div>
									</div>
								</div>
							</motion.div>
						</Container>
					</div>
				</section>

				{/* Professional Summary */}
				<section className="bg-background py-16">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-4xl text-center"
						>
							<h2 className="mb-4 text-3xl font-bold text-stone-900 md:text-4xl dark:text-stone-100">
								What I Do
							</h2>
							<p className="text-lg leading-relaxed text-stone-600 md:text-xl dark:text-stone-400">
								Senior Front-End Developer with 15+ years of experience building scalable,
								high-performance web apps and company websites. Skilled in React, Next.js,
								TypeScript, and Tailwind CSS with a strong focus on accessibility, SEO, and client
								success. Technical lead behind IntraWeb Technologies&apos; digital presence and
								AI-driven content collaboration tooling (SynaplyAI).
							</p>
						</motion.div>
					</Container>
				</section>

				{/* Resume Accordion Section */}
				<section className="bg-muted py-20">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-6xl"
						>
							<div className="mb-16 text-center">
								<h2 className="mb-4 text-3xl font-bold text-stone-900 md:text-4xl dark:text-stone-100">
									My Journey
								</h2>
								<p className="text-lg text-stone-600 dark:text-stone-400">
									From teaching to development: A story of resilience, learning, and growth
								</p>
							</div>

							{/* Timeline Container */}
							<div className="relative">
								{/* Vertical Timeline Line */}
								<div className="absolute left-8 top-0 bottom-0 w-0.5 bg-gradient-to-b from-stone-300 via-stone-400 to-stone-300 dark:from-stone-600 dark:via-stone-500 dark:to-stone-600 md:left-1/2 md:-translate-x-px"></div>

								{/* Timeline Items */}
								<div className="space-y-12">
									{/* Teaching Era */}
									<motion.div
										initial={{ opacity: 0, x: -30 }}
										whileInView={{ opacity: 1, x: 0 }}
										transition={{ duration: 0.8, ease: 'easeOut' }}
										viewport={{ once: true }}
										className="relative flex items-start gap-8 md:gap-12"
									>
										{/* Timeline Dot */}
										<div className="absolute left-6 z-10 flex h-4 w-4 items-center justify-center rounded-full bg-stone-900 shadow-lg md:left-1/2 md:-translate-x-2 dark:bg-stone-100">
											<div className="h-2 w-2 rounded-full bg-white dark:bg-stone-900"></div>
										</div>

										{/* Content */}
										<div className="ml-16 flex-1 md:ml-0 md:flex-none md:w-1/2 md:pr-12">
											<div className="rounded-lg border border-border bg-card p-6 shadow-sm">
												<div className="mb-4 flex items-center gap-3">
													<div className="flex h-12 w-12 items-center justify-center rounded-lg bg-stone-100 dark:bg-stone-800">
														<GraduationCapIcon className="h-6 w-6 text-stone-600 dark:text-stone-400" />
													</div>
													<div>
														<h3 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
															The Teaching Years
														</h3>
														<p className="text-sm text-stone-500 dark:text-stone-400">2005 - 2009</p>
													</div>
												</div>
												<p className="text-stone-600 dark:text-stone-400">
													As Web Development Program Director at Anthem Institute, I discovered my passion for making complex concepts accessible. 
													Teaching HTML, CSS, JavaScript, and PHP to students across multiple campuses taught me that <strong className="text-stone-900 dark:text-stone-100">code should be teachable and maintainable</strong> – 
													principles that still guide my development approach today.
												</p>
											</div>
										</div>

										{/* Spacer for alternating layout */}
										<div className="hidden md:block md:w-1/2"></div>
									</motion.div>

									{/* Challenge & Recovery */}
									<motion.div
										initial={{ opacity: 0, x: 30 }}
										whileInView={{ opacity: 1, x: 0 }}
										transition={{ duration: 0.8, ease: 'easeOut' }}
										viewport={{ once: true }}
										className="relative flex items-start gap-8 md:gap-12"
									>
										{/* Timeline Dot */}
										<div className="absolute left-6 z-10 flex h-4 w-4 items-center justify-center rounded-full bg-stone-900 shadow-lg md:left-1/2 md:-translate-x-2 dark:bg-stone-100">
											<div className="h-2 w-2 rounded-full bg-white dark:bg-stone-900"></div>
										</div>

										{/* Spacer for alternating layout */}
										<div className="hidden md:block md:w-1/2"></div>

										{/* Content */}
										<div className="ml-16 flex-1 md:ml-0 md:flex-none md:w-1/2 md:pl-12">
											<div className="rounded-lg border border-border bg-card p-6 shadow-sm">
												<div className="mb-4 flex items-center gap-3">
													<div className="flex h-12 w-12 items-center justify-center rounded-lg bg-stone-100 dark:bg-stone-800">
														<StarIcon className="h-6 w-6 text-stone-600 dark:text-stone-400" />
													</div>
													<div>
														<h3 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
															Overcoming Challenges
														</h3>
														<p className="text-sm text-stone-500 dark:text-stone-400">Personal Growth</p>
													</div>
												</div>
												<p className="text-stone-600 dark:text-stone-400">
													Life threw unexpected challenges my way, including a stroke that tested my resilience. 
													Through recovery, I learned that <strong className="text-stone-900 dark:text-stone-100">perseverance and adaptability are as crucial in life as they are in code</strong>. 
													This experience deepened my understanding of accessibility and inclusive design – principles I now champion in every project.
												</p>
											</div>
										</div>
									</motion.div>

									{/* Evolution to Modern Development */}
									<motion.div
										initial={{ opacity: 0, x: -30 }}
										whileInView={{ opacity: 1, x: 0 }}
										transition={{ duration: 0.8, ease: 'easeOut' }}
										viewport={{ once: true }}
										className="relative flex items-start gap-8 md:gap-12"
									>
										{/* Timeline Dot */}
										<div className="absolute left-6 z-10 flex h-4 w-4 items-center justify-center rounded-full bg-stone-900 shadow-lg md:left-1/2 md:-translate-x-2 dark:bg-stone-100">
											<div className="h-2 w-2 rounded-full bg-white dark:bg-stone-900"></div>
										</div>

										{/* Content */}
										<div className="ml-16 flex-1 md:ml-0 md:flex-none md:w-1/2 md:pr-12">
											<div className="rounded-lg border border-border bg-card p-6 shadow-sm">
												<div className="mb-4 flex items-center gap-3">
													<div className="flex h-12 w-12 items-center justify-center rounded-lg bg-stone-100 dark:bg-stone-800">
														<BracketsIcon className="h-6 w-6 text-stone-600 dark:text-stone-400" />
													</div>
													<div>
														<h3 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
															Modern Development
														</h3>
														<p className="text-sm text-stone-500 dark:text-stone-400">2009 - Present</p>
													</div>
												</div>
												<p className="text-stone-600 dark:text-stone-400">
													My journey evolved from WordPress customization to building enterprise-scale applications with React, Next.js, and AI integrations. 
													The educator in me still shines through – I believe in <strong className="text-stone-900 dark:text-stone-100">writing code that tells a story</strong>, 
													documenting thoroughly, and mentoring team members to ensure every project is built for the long term.
												</p>
											</div>
										</div>

										{/* Spacer for alternating layout */}
										<div className="hidden md:block md:w-1/2"></div>
									</motion.div>

									{/* Current Mission */}
									<motion.div
										initial={{ opacity: 0, x: 30 }}
										whileInView={{ opacity: 1, x: 0 }}
										transition={{ duration: 0.8, ease: 'easeOut' }}
										viewport={{ once: true }}
										className="relative flex items-start gap-8 md:gap-12"
									>
										{/* Timeline Dot */}
										<div className="absolute left-6 z-10 flex h-4 w-4 items-center justify-center rounded-full bg-gradient-to-r from-stone-600 to-stone-800 shadow-lg md:left-1/2 md:-translate-x-2 dark:from-stone-300 dark:to-stone-100">
											<div className="h-2 w-2 rounded-full bg-white dark:bg-stone-900"></div>
										</div>

										{/* Spacer for alternating layout */}
										<div className="hidden md:block md:w-1/2"></div>

										{/* Content */}
										<div className="ml-16 flex-1 md:ml-0 md:flex-none md:w-1/2 md:pl-12">
											<div className="rounded-lg border-2 border-primary/20 bg-gradient-to-br from-card to-accent/10 p-6 shadow-lg">
												<div className="mb-4 flex items-center gap-3">
													<div className="flex h-12 w-12 items-center justify-center rounded-lg bg-gradient-to-br from-primary/10 to-primary/20">
														<LightbulbIcon className="h-6 w-6 text-primary" />
													</div>
													<div>
														<h3 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
															Today's Mission
														</h3>
														<p className="text-sm text-stone-500 dark:text-stone-400">Building the Future</p>
													</div>
												</div>
												<p className="text-stone-600 dark:text-stone-400">
													As Founder and Lead Developer at IntraWeb Technologies, I'm building the future of web development with AI-driven solutions like SynaplyAI. 
													My mission: <strong className="text-stone-900 dark:text-stone-100">creating technology that empowers people</strong> – 
													whether that's through accessible interfaces, intelligent automation, or mentoring the next generation of developers.
												</p>
											</div>
										</div>
									</motion.div>
								</div>
							</div>

							{/* Philosophy Section */}
							<motion.div
								initial={{ opacity: 0, y: 20 }}
								whileInView={{ opacity: 1, y: 0 }}
								transition={{ duration: 0.8, ease: 'easeOut', delay: 0.3 }}
								viewport={{ once: true }}
								className="mt-16 rounded-lg border border-border bg-card p-8 shadow-sm"
							>
								<div className="text-center">
									<h3 className="mb-4 text-2xl font-bold text-stone-900 dark:text-stone-100">
										My Development Philosophy
									</h3>
									<p className="text-lg leading-relaxed text-stone-600 dark:text-stone-400">
										<strong className="text-stone-900 dark:text-stone-100">Code is communication.</strong> Every line should be clear, 
										every function should tell a story, and every system should be built with future developers in mind. 
										This educator mindset drives me to create solutions that are not just functional, but truly maintainable and scalable.
									</p>
								</div>
							</motion.div>
						</motion.div>
					</Container>
				</section>

				{/* Value Proposition Cards Section */}
				<section className="bg-background py-20">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-7xl"
						>
							{/* Section Header */}
							<div className="mb-16 text-center">
								<h2 className="mb-4 text-3xl font-bold text-stone-900 md:text-4xl dark:text-stone-100">
									Why Choose Me
								</h2>
								<p className="text-lg text-stone-600 dark:text-stone-400 max-w-3xl mx-auto">
									Proven results that drive business growth through exceptional web development and client success
								</p>
							</div>

							{/* Value Proposition Cards Grid */}
							<div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
								{/* Project Delivery Card */}
								<motion.div
									initial={{ opacity: 0, y: 30 }}
									whileInView={{ opacity: 1, y: 0 }}
									transition={{ duration: 0.6, delay: 0.1, ease: 'easeOut' }}
									viewport={{ once: true }}
									className="group relative overflow-hidden rounded-2xl border border-stone-200 bg-white p-8 shadow-lg transition-all duration-300 hover:shadow-2xl hover:border-stone-300 dark:border-stone-700 dark:bg-stone-900 dark:hover:border-stone-600"
								>
									{/* Card Background Gradient */}
									<div className="absolute inset-0 bg-gradient-to-br from-stone-50/50 via-transparent to-stone-100/30 opacity-0 transition-opacity duration-300 group-hover:opacity-100 dark:from-stone-800/20 dark:to-stone-700/10" />
									
									{/* Icon */}
									<div className="relative mb-6 flex h-16 w-16 items-center justify-center rounded-xl bg-stone-600 shadow-lg group-hover:bg-stone-700 transition-colors duration-300 dark:bg-stone-500 dark:group-hover:bg-stone-400">
										<CheckCircleIcon className="h-8 w-8 text-white" />
									</div>
									
									{/* Content */}
									<div className="relative">
										<h3 className="mb-3 text-xl font-bold text-stone-900 dark:text-stone-100">
											Project Delivery
										</h3>
										<div className="mb-4 text-3xl font-bold text-stone-700 dark:text-stone-300">
											25+ Projects
										</div>
										<p className="text-stone-600 dark:text-stone-400 leading-relaxed">
											Successfully delivered complex web applications and digital solutions across various industries, 
											from e-commerce platforms to AI-driven collaboration tools.
										</p>
									</div>
								</motion.div>

								{/* Client Success Card */}
								<motion.div
									initial={{ opacity: 0, y: 30 }}
									whileInView={{ opacity: 1, y: 0 }}
									transition={{ duration: 0.6, delay: 0.2, ease: 'easeOut' }}
									viewport={{ once: true }}
									className="group relative overflow-hidden rounded-2xl border border-stone-200 bg-white p-8 shadow-lg transition-all duration-300 hover:shadow-2xl hover:border-stone-300 dark:border-stone-700 dark:bg-stone-900 dark:hover:border-stone-600"
								>
									{/* Card Background Gradient */}
									<div className="absolute inset-0 bg-gradient-to-br from-stone-50/50 via-transparent to-stone-100/30 opacity-0 transition-opacity duration-300 group-hover:opacity-100 dark:from-stone-800/20 dark:to-stone-700/10" />
									
									{/* Icon */}
									<div className="relative mb-6 flex h-16 w-16 items-center justify-center rounded-xl bg-stone-600 shadow-lg group-hover:bg-stone-700 transition-colors duration-300 dark:bg-stone-500 dark:group-hover:bg-stone-400">
										<UsersIcon className="h-8 w-8 text-white" />
									</div>
									
									{/* Content */}
									<div className="relative">
										<h3 className="mb-3 text-xl font-bold text-stone-900 dark:text-stone-100">
											Client Success
										</h3>
										<div className="mb-4 text-3xl font-bold text-stone-700 dark:text-stone-300">
											100% Retention
										</div>
										<p className="text-stone-600 dark:text-stone-400 leading-relaxed">
											Maintained perfect client retention through exceptional service delivery, clear communication, 
											and exceeding project expectations every time.
										</p>
									</div>
								</motion.div>

								{/* Response Time Card */}
								<motion.div
									initial={{ opacity: 0, y: 30 }}
									whileInView={{ opacity: 1, y: 0 }}
									transition={{ duration: 0.6, delay: 0.3, ease: 'easeOut' }}
									viewport={{ once: true }}
									className="group relative overflow-hidden rounded-2xl border border-stone-200 bg-white p-8 shadow-lg transition-all duration-300 hover:shadow-2xl hover:border-stone-300 dark:border-stone-700 dark:bg-stone-900 dark:hover:border-stone-600"
								>
									{/* Card Background Gradient */}
									<div className="absolute inset-0 bg-gradient-to-br from-stone-50/50 via-transparent to-stone-100/30 opacity-0 transition-opacity duration-300 group-hover:opacity-100 dark:from-stone-800/20 dark:to-stone-700/10" />
									
									{/* Icon */}
									<div className="relative mb-6 flex h-16 w-16 items-center justify-center rounded-xl bg-stone-600 shadow-lg group-hover:bg-stone-700 transition-colors duration-300 dark:bg-stone-500 dark:group-hover:bg-stone-400">
										<ClockIcon className="h-8 w-8 text-white" />
									</div>
									
									{/* Content */}
									<div className="relative">
										<h3 className="mb-3 text-xl font-bold text-stone-900 dark:text-stone-100">
											Response Time
										</h3>
										<div className="mb-4 text-3xl font-bold text-stone-700 dark:text-stone-300">
											24h Response
										</div>
										<p className="text-stone-600 dark:text-stone-400 leading-relaxed">
											Committed to rapid communication and quick turnaround times. Your project needs are 
											my priority with guaranteed response within 24 hours.
										</p>
									</div>
								</motion.div>

								{/* AI-Enhanced Development Card */}
								<motion.div
									initial={{ opacity: 0, y: 30 }}
									whileInView={{ opacity: 1, y: 0 }}
									transition={{ duration: 0.6, delay: 0.4, ease: 'easeOut' }}
									viewport={{ once: true }}
									className="group relative overflow-hidden rounded-2xl border border-stone-200 bg-white p-8 shadow-lg transition-all duration-300 hover:shadow-2xl hover:border-stone-300 dark:border-stone-700 dark:bg-stone-900 dark:hover:border-stone-600"
								>
									{/* Card Background Gradient */}
									<div className="absolute inset-0 bg-gradient-to-br from-stone-50/50 via-transparent to-stone-100/30 opacity-0 transition-opacity duration-300 group-hover:opacity-100 dark:from-stone-800/20 dark:to-stone-700/10" />
									
									{/* Icon */}
									<div className="relative mb-6 flex h-16 w-16 items-center justify-center rounded-xl bg-stone-600 shadow-lg group-hover:bg-stone-700 transition-colors duration-300 dark:bg-stone-500 dark:group-hover:bg-stone-400">
										<ZapIcon className="h-8 w-8 text-white" />
									</div>
									
									{/* Content */}
									<div className="relative">
										<h3 className="mb-3 text-xl font-bold text-stone-900 dark:text-stone-100">
											AI-Enhanced Development
										</h3>
										<div className="mb-4 text-3xl font-bold text-stone-700 dark:text-stone-300">
											Future-Ready
										</div>
										<p className="text-stone-600 dark:text-stone-400 leading-relaxed">
											Leveraging cutting-edge AI tools and modern development practices to build 
											intelligent, scalable solutions that adapt to your business needs.
										</p>
									</div>
								</motion.div>

								{/* Accessibility & SEO Card */}
								<motion.div
									initial={{ opacity: 0, y: 30 }}
									whileInView={{ opacity: 1, y: 0 }}
									transition={{ duration: 0.6, delay: 0.5, ease: 'easeOut' }}
									viewport={{ once: true }}
									className="group relative overflow-hidden rounded-2xl border border-stone-200 bg-white p-8 shadow-lg transition-all duration-300 hover:shadow-2xl hover:border-stone-300 dark:border-stone-700 dark:bg-stone-900 dark:hover:border-stone-600"
								>
									{/* Card Background Gradient */}
									<div className="absolute inset-0 bg-gradient-to-br from-stone-50/50 via-transparent to-stone-100/30 opacity-0 transition-opacity duration-300 group-hover:opacity-100 dark:from-stone-800/20 dark:to-stone-700/10" />
									
									{/* Icon */}
									<div className="relative mb-6 flex h-16 w-16 items-center justify-center rounded-xl bg-stone-600 shadow-lg group-hover:bg-stone-700 transition-colors duration-300 dark:bg-stone-500 dark:group-hover:bg-stone-400">
										<TrendingUpIcon className="h-8 w-8 text-white" />
									</div>
									
									{/* Content */}
									<div className="relative">
										<h3 className="mb-3 text-xl font-bold text-stone-900 dark:text-stone-100">
											Accessibility & SEO
										</h3>
										<div className="mb-4 text-3xl font-bold text-stone-700 dark:text-stone-300">
											WCAG Compliant
										</div>
										<p className="text-stone-600 dark:text-stone-400 leading-relaxed">
											Building inclusive, accessible web experiences that reach all users while 
											optimizing for search engines to maximize your digital presence.
										</p>
									</div>
								</motion.div>

								{/* Process Excellence Card */}
								<motion.div
									initial={{ opacity: 0, y: 30 }}
									whileInView={{ opacity: 1, y: 0 }}
									transition={{ duration: 0.6, delay: 0.6, ease: 'easeOut' }}
									viewport={{ once: true }}
									className="group relative overflow-hidden rounded-2xl border border-stone-200 bg-white p-8 shadow-lg transition-all duration-300 hover:shadow-2xl hover:border-stone-300 dark:border-stone-700 dark:bg-stone-900 dark:hover:border-stone-600"
								>
									{/* Card Background Gradient */}
									<div className="absolute inset-0 bg-gradient-to-br from-stone-50/50 via-transparent to-stone-100/30 opacity-0 transition-opacity duration-300 group-hover:opacity-100 dark:from-stone-800/20 dark:to-stone-700/10" />
									
									{/* Icon */}
									<div className="relative mb-6 flex h-16 w-16 items-center justify-center rounded-xl bg-stone-600 shadow-lg group-hover:bg-stone-700 transition-colors duration-300 dark:bg-stone-500 dark:group-hover:bg-stone-400">
										<StarIcon className="h-8 w-8 text-white" />
									</div>
									
									{/* Content */}
									<div className="relative">
										<h3 className="mb-3 text-xl font-bold text-stone-900 dark:text-stone-100">
											Process Excellence
										</h3>
										<div className="mb-4 text-3xl font-bold text-stone-700 dark:text-stone-300">
											15+ Years
										</div>
										<p className="text-stone-600 dark:text-stone-400 leading-relaxed">
											Refined development processes through years of experience, ensuring consistent 
											quality, on-time delivery, and seamless project execution.
										</p>
									</div>
								</motion.div>
							</div>

							{/* Bottom CTA */}
							<motion.div
								initial={{ opacity: 0, y: 20 }}
								whileInView={{ opacity: 1, y: 0 }}
								transition={{ duration: 0.8, delay: 0.7, ease: 'easeOut' }}
								viewport={{ once: true }}
								className="mt-16 text-center"
							>
								<p className="mb-6 text-lg text-stone-600 dark:text-stone-400">
									Ready to experience these results for your project?
								</p>
								<Button
									size="lg"
									className="bg-stone-900 text-white hover:bg-stone-800 shadow-lg hover:shadow-xl transition-all duration-300 dark:bg-stone-100 dark:text-stone-900 dark:hover:bg-stone-200"
									asChild
								>
									<Link href="/contact">
										Start Your Project
										<ArrowRightIcon className="ml-2 h-5 w-5" />
									</Link>
								</Button>
							</motion.div>
						</motion.div>
					</Container>
				</section>

				{/* Experience Timeline Section */}
				<section className="bg-muted py-20">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-6xl"
						>
							<div className="mb-16 text-center">
								<h2 className="mb-4 text-3xl font-bold text-stone-900 md:text-4xl dark:text-stone-100">
									Career Journey
								</h2>
								<p className="mb-8 text-lg text-stone-600 dark:text-stone-400">
									My professional experience and key achievements over 15+ years
								</p>
								
								{/* Career Progression Summary */}
								<div className="mx-auto max-w-4xl rounded-lg border border-stone-200 bg-gradient-to-r from-stone-50 to-stone-100 p-6 dark:border-stone-700 dark:from-stone-800 dark:to-stone-900">
									<div className="grid grid-cols-1 gap-6 md:grid-cols-3">
										<div className="text-center">
											<div className="mb-2 text-3xl font-bold text-primary">15+</div>
											<div className="text-sm text-stone-600 dark:text-stone-400">Years Experience</div>
										</div>
										<div className="text-center">
											<div className="mb-2 text-3xl font-bold text-primary">6</div>
											<div className="text-sm text-stone-600 dark:text-stone-400">Companies</div>
										</div>
										<div className="text-center">
											<div className="mb-2 text-3xl font-bold text-primary">AI</div>
											<div className="text-sm text-stone-600 dark:text-stone-400">Innovation Focus</div>
										</div>
									</div>
									<div className="mt-4 text-center">
										<p className="text-sm text-stone-600 dark:text-stone-400">
											From teaching web development to leading AI-driven projects, my journey spans the evolution of modern web technologies.
										</p>
									</div>
								</div>
							</div>

							{/* Experience Timeline */}
							<Timeline>
								{experience.map((job, index) => (
									<TimelineItem
										key={index}
										title={job.title}
										company={job.company}
										period={job.period}
										location={job.location}
										description={job.description}
										achievements={job.achievements}
										index={index}
										isLast={index === experience.length - 1}
									/>
								))}
							</Timeline>
						</motion.div>
					</Container>
				</section>

				{/* Visual Skills Showcase Section */}
				<section className="bg-background py-20">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-7xl"
						>
							<VisualSkillsShowcase />
						</motion.div>
					</Container>
				</section>

				{/* Additional Sections */}
				<section className="bg-muted py-20">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-4xl"
						>
							<div className="mb-12 text-center">
								<h2 className="mb-4 text-3xl font-bold text-stone-900 md:text-4xl dark:text-stone-100">
									Professional Background
								</h2>
								<p className="text-lg text-stone-600 dark:text-stone-400">
									Explore my experience, skills, and qualifications
								</p>
							</div>

							<Accordion type="single" collapsible className="w-full space-y-4">
								{/* Experience */}
								<AccordionItem
									value="experience"
									className="rounded-lg border border-border bg-card shadow-sm transition-all duration-300 hover:border-border hover:shadow-md"
								>
									<AccordionTrigger className="rounded-t-lg px-6 py-4 text-left transition-colors duration-200">
										<div className="flex items-center gap-3">
											<BriefcaseIcon className="h-5 w-5 text-muted-foreground transition-colors duration-200" />
											<span className="text-lg font-semibold">Professional Experience</span>
										</div>
									</AccordionTrigger>
									<AccordionContent className="px-6">
										<div className="space-y-8">
											{experience.map((job, index) => (
												<div
													key={index}
													className="border-l-4 border-primary/40 pl-6"
												>
													<div className="mb-2 flex flex-col sm:flex-row sm:items-center sm:justify-between">
														<h3 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
															{job.title}
														</h3>
														<div className="mt-1 text-sm text-stone-500 sm:mt-0 dark:text-stone-400">
															{job.period}
														</div>
													</div>
													<div className="mb-3 flex items-center gap-2 text-stone-600 dark:text-stone-400">
														<span className="font-medium">{job.company}</span>
														<span>•</span>
														<span>{job.location}</span>
													</div>
													<p className="mb-4 text-stone-600 dark:text-stone-400">
														{job.description}
													</p>
													<ul className="space-y-2">
														{job.achievements.map((achievement, idx) => (
															<li
																key={idx}
																className="flex items-start gap-2 text-sm text-stone-600 dark:text-stone-400"
															>
																<StarIcon className="mt-1 h-3 w-3 flex-shrink-0 text-stone-400 dark:text-stone-500" />
																{achievement}
															</li>
														))}
													</ul>
												</div>
											))}
										</div>
									</AccordionContent>
								</AccordionItem>

								{/* Education */}
								<AccordionItem
									value="education"
									className="rounded-lg border border-border bg-card shadow-sm transition-all duration-300 hover:border-border hover:shadow-md"
								>
									<AccordionTrigger className="rounded-t-lg px-6 py-4 text-left transition-colors duration-200">
										<div className="flex items-center gap-3">
											<GraduationCapIcon className="h-5 w-5 text-muted-foreground transition-colors duration-200" />
											<span className="text-lg font-semibold">Education & Certifications</span>
										</div>
									</AccordionTrigger>
									<AccordionContent className="px-6">
										<div className="space-y-6">
											{education.map((edu, index) => (
												<div
													key={index}
													className="border-l-4 border-primary/40 pl-6"
												>
													<div className="mb-2 flex flex-col sm:flex-row sm:items-center sm:justify-between">
														<h4 className="text-lg font-semibold text-stone-900 dark:text-stone-100">
															{edu.degree}
														</h4>
														<div className="mt-1 text-sm text-stone-500 sm:mt-0 dark:text-stone-400">
															{edu.period}
														</div>
													</div>
													<div className="mb-2 flex items-center gap-2 text-stone-600 dark:text-stone-400">
														<span>{edu.school}</span>
														<span>•</span>
														<span>{edu.location}</span>
													</div>
													<p className="text-sm text-stone-600 dark:text-stone-400">
														{edu.description}
													</p>
												</div>
											))}

											<div className="border-t border-stone-200 pt-4 dark:border-stone-600">
												<h4 className="mb-3 font-semibold text-stone-900 dark:text-stone-100">
													Certifications
												</h4>
												<div className="space-y-2">
													{certifications.map((cert, index) => (
														<div key={index} className="flex items-center justify-between">
															<span className="text-stone-600 dark:text-stone-400">
																{cert.name}
															</span>
															<span className="text-sm text-stone-500 dark:text-stone-500">
																{cert.year}
															</span>
														</div>
													))}
												</div>
											</div>
										</div>
									</AccordionContent>
								</AccordionItem>

								{/* Approach */}
								<AccordionItem
									value="approach"
									className="rounded-lg border border-border bg-card shadow-sm transition-all duration-300 hover:border-border hover:shadow-md"
								>
									<AccordionTrigger className="rounded-t-lg px-6 py-4 text-left transition-colors duration-200">
										<div className="flex items-center gap-3">
											<BookOpenIcon className="h-5 w-5 text-muted-foreground transition-colors duration-200" />
											<span className="text-lg font-semibold">My Approach & Philosophy</span>
										</div>
									</AccordionTrigger>
									<AccordionContent className="px-6">
										<div className="space-y-4">
											<div>
												<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
													Development Philosophy
												</h4>
												<p className="text-stone-600 dark:text-stone-400">
													I believe in writing clean, maintainable code and staying up-to-date with
													the latest industry best practices. I&apos;m passionate about AI-driven
													development and finding innovative ways to improve the development
													workflow.
												</p>
											</div>
											<div>
												<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
													Work Style
												</h4>
												<p className="text-stone-600 dark:text-stone-400">
													I thrive in collaborative environments and believe in the power of clear
													communication. I&apos;m committed to delivering high-quality solutions
													that exceed expectations while meeting deadlines.
												</p>
											</div>
											<div>
												<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
													Continuous Learning
												</h4>
												<p className="text-stone-600 dark:text-stone-400">
													When I&apos;m not coding, you&apos;ll find me exploring new technologies,
													contributing to open source projects, or sharing knowledge with the
													developer community.
												</p>
											</div>
										</div>
									</AccordionContent>
								</AccordionItem>
							</Accordion>
						</motion.div>
					</Container>
				</section>

				{/* CTA Section */}
				<section className="bg-background py-20">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-4xl text-center"
						>
							<div className="rounded-lg border border-border bg-accent p-8 shadow-sm">
								<h2 className="mb-4 text-3xl font-bold text-stone-900 dark:text-stone-100">
									Let&apos;s Work Together
								</h2>
								<p className="mb-8 text-lg text-stone-600 dark:text-stone-400">
									I&apos;m available for freelance projects and consulting opportunities. Whether
									you need a complete application built from scratch or help optimizing an existing
									codebase, I&apos;d love to hear about your project.
								</p>
								<div className="flex flex-col justify-center gap-4 sm:flex-row">
									<Button
										size="lg"
										asChild
									>
										<Link href="/contact">
											Start a Project
											<ArrowRightIcon className="ml-2 h-4 w-4" />
										</Link>
									</Button>
									<Button
										size="lg"
										variant="outline"
										asChild
									>
										<Link href="/projects">View My Projects</Link>
									</Button>
								</div>
							</div>
						</motion.div>
					</Container>
				</section>
			</main>

			{/* Footer */}
			<Footer publication={publication} />

			{/* Chatbot */}
			<Chatbot />
		</AppProvider>
	);
}

/**
 * Static props generation for About page with comprehensive error handling
 * @returns Promise with publication data or fallback data
 */
export const getStaticProps: GetStaticProps<Props> = async () => {
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST || 'mindware.hashnode.dev';

	// Validate environment variables
	if (!process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT) {
		console.warn('NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT environment variable is not set');
	}

	try {
		const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			PostsByPublicationDocument,
			{
				first: 0,
				host: host,
			},
		);

		const publication = data.publication;
		if (!publication) {
			console.error('No publication data found for host:', host);
			return {
				notFound: true,
			};
		}

		// Validate publication data structure
		if (!publication.title && !publication.displayTitle) {
			console.warn('Publication missing title and displayTitle');
		}

		return {
			props: {
				publication,
			},
			revalidate: 1,
		};
	} catch (error) {
		console.error('Error fetching publication data for About page:', error);
		
		// Enhanced fallback response with better error handling
		const fallbackPublication = {
			id: 'fallback-about',
			title: 'John Schibelli',
			displayTitle: 'John Schibelli',
			descriptionSEO: 'Senior Front-End Developer with 15+ years of experience building scalable, high-performance web applications.',
			url: 'https://johnschibelli.com',
			posts: {
				totalDocuments: 0,
			},
			preferences: {
				logo: null,
			},
			author: {
				name: 'John Schibelli',
				profilePicture: null,
			},
			followersCount: 0,
			isTeam: false,
			favicon: null,
			ogMetaData: {
				image: null,
			},
		};

		return {
			props: {
				publication: fallbackPublication as any,
			},
			revalidate: 1,
		};
	}
};
