/* eslint-disable @next/next/no-img-element */
import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import { motion } from 'framer-motion';
import request from 'graphql-request';
import {
	ArrowRightIcon,
	BookOpenIcon,
	BracketsIcon,
	BriefcaseIcon,
	CalendarIcon,
	GraduationCapIcon,
	LightbulbIcon,
	MapPinIcon,
	StarIcon,
} from 'lucide-react';
import { GetStaticProps } from 'next';
import Link from 'next/link';
import { AppProvider } from '../components/contexts/appContext';
import Chatbot from '../components/features/chatbot/Chatbot';
import ModernHeader from '../components/features/navigation/modern-header';
import { Container } from '../components/shared/container';
import { Footer } from '../components/shared/footer';
import { SEOHead } from '../components/shared/seo-head';
import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from '../components/ui/accordion';
import { Badge, Button } from '../components/ui';
import { generatePersonStructuredData } from '../lib/structured-data';
import {
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT || 'https://gql.hashnode.com/';

type Props = {
	publication: PublicationFragment;
};

/**
 * About page component displaying professional information and experience
 * @param publication - Publication data from Hashnode
 * @returns JSX element for the about page
 */
export default function About({ publication }: Props) {
	// Import skills from centralized data source to avoid duplication
	let skills: Record<string, string[]> = {};
	
	try {
		const { skills: skillsData } = require('../../data/skills');
		
		// Validate skills data structure
		if (Array.isArray(skillsData)) {
			// Group skills by category for display with proper error handling
			skills = skillsData.reduce((acc: Record<string, string[]>, skill: any) => {
				if (skill && typeof skill === 'object' && skill.category && skill.name) {
					if (!acc[skill.category]) {
						acc[skill.category] = [];
					}
					acc[skill.category].push(skill.name);
				}
				return acc;
			}, {});
		} else {
			console.warn('Skills data is not in expected array format');
		}
	} catch (error) {
		console.error('Error loading skills data:', error);
		// Fallback to empty skills object to prevent page crash
		skills = {};
	}

	const experience = [
		{
			title: 'Senior Front-End Developer',
			company: 'IntraWeb Technology',
			period: '2020 - Present',
			location: 'Montville, NJ',
			description: 'Lead front-end for company site and client projects; incubated SynaplyAI.',
			achievements: [
				'Built the IntraWeb Technologies website with Next.js, React, TypeScript, and Tailwind CSS; shipped an accessible, SEO-optimized presence.',
				'Delivered custom WordPress and Shopify builds emphasizing mobile performance and SEO for clients including KAL Design.',
				'Scoped requirements, owned timelines, and served as primary client liaison to ensure quality delivery and satisfaction.',
				'Incubated SynaplyAI (multi-tenant AI content collaboration) with front-end architecture, OpenAI integrations, real-time collab editing, and adaptive AI content generation.',
			],
		},
		{
			title: 'Full-Stack Developer',
			company: 'ColorStreet',
			period: '2024',
			location: 'Totowa, NJ',
			description: 'Contributed to e-commerce platform quality and integrations.',
			achievements: [
				'Implemented automated UI testing with Playwright, improving reliability across releases.',
				'Integrated and validated Nest.js APIs; ensured stable data flow and interface alignment.',
				'Partnered with QA, design, and product to support sprint delivery and UI improvements.',
			],
		},
		{
			title: 'Senior Front-End Developer',
			company: 'Executive Five Star',
			period: '2016 - 2020',
			location: 'Montville, NJ',
			description: "Owned front-end for the company's car service site and online booking.",
			achievements: [
				'Developed and maintained the primary WordPress site with improved usability and mobile responsiveness.',
				'Integrated Limo Anywhere API for real-time reservations and back-office sync.',
				'Streamlined dispatch workflows by connecting booking front-end to internal systems.',
			],
		},
		{
			title: 'Front-End Developer',
			company: 'Robert Half Technology',
			period: '2013 - 2016',
			location: 'Parsippany, NJ',
			description: 'Built enterprise UIs and internal tooling in JavaScript ecosystems.',
			achievements: [
				'Developed UIs for internal financial platforms using JavaScript, jQuery, and Bootstrap to improve reporting workflows.',
				'Built interactive presentation tools for pharmaceutical clients using Veeva CRM and HTML5.',
				'Delivered front-end features aligned with enterprise UX guidelines in Agile cycles.',
				'Led multiple internal WordPress projects and mentored junior developers on front-end best practices.',
			],
		},
		{
			title: 'Web Developer (Contract)',
			company: 'Level-Nine Creative',
			period: '2009 - 2013',
			location: 'Merritt Island, FL',
			description: 'Delivered custom WordPress sites for small businesses and agencies.',
			achievements: [
				'Designed and developed custom websites using WordPress, PHP, JavaScript, and CSS.',
				'Built reusable UI components for responsive, cross-browser performance.',
				'Customized themes/plugins to support marketing workflows and SEO.',
			],
		},
		{
			title: 'Web Development Program Director',
			company: 'Anthem Institute',
			period: '2005 - 2009',
			location: 'Parsippany, NJ',
			description: 'Led curriculum and instruction across multiple campuses.',
			achievements: [
				'Taught HTML, CSS, JavaScript, PHP, and MySQL; built industry-ready skills.',
				'Managed a team of 8 instructors across 4 campuses; ensured curriculum alignment.',
				'Oversaw accreditation compliance; partnered with Pearson VUE for certification programs.',
			],
		},
	];

	const education = [
		{
			degree: 'Web & Graphic Design',
			school: 'The Chubb Institute',
			period: '2004',
			location: 'New Jersey',
			description: 'Diploma in Web & Graphic Design',
		},
	];

	const certifications = [
		{
			name: '15+ Years Experience',
			issuer: 'Web Development',
			year: '2005-2025',
		},
	];

	return (
		<AppProvider publication={publication}>
			<SEOHead
				title={`About - ${publication.displayTitle || publication.title}`}
				description="Learn more about John Schibelli, Senior Front-End Developer specializing in React, Next.js, TypeScript, and AI-driven development."
				keywords={[
					'John Schibelli',
					'Front-End Developer',
					'React Developer',
					'Next.js Developer',
					'TypeScript Developer',
					'Web Development',
					'Professional Experience',
					'Skills',
					'Portfolio',
				]}
				canonical="/about"
				ogImage={getAutogeneratedPublicationOG(publication)}
				ogType="profile"
				structuredData={generatePersonStructuredData({
					name: 'John Schibelli',
					description: 'Senior Front-End Developer with 15+ years of experience building scalable, high-performance web applications.',
					url: 'https://johnschibelli.com',
					jobTitle: 'Senior Front-End Developer',
					knowsAbout: [
						'JavaScript (ES6+)',
						'TypeScript',
						'React',
						'Next.js',
						'Node.js',
						'HTML5',
						'CSS3',
						'Tailwind CSS',
						'GraphQL',
						'REST APIs',
						'Web Accessibility',
						'SEO Optimization',
						'Performance Optimization',
						'UI/UX Design',
						'Testing',
						'DevOps',
						'Cloud Computing',
					],
					alumniOf: [
						{
							name: 'The Chubb Institute',
						},
					],
					hasCredential: [
						{
							name: '15+ Years Experience',
							credentialCategory: 'Work Experience',
							recognizedBy: {
								name: 'Web Development Industry',
							},
						},
					],
					sameAs: [
						'https://linkedin.com/in/johnschibelli',
						'https://github.com/johnschibelli',
						'https://twitter.com/johnschibelli',
					],
				})}
			/>

			<ModernHeader publication={publication} />

			<main className="min-h-screen bg-background">
				{/* Enhanced Hero Section */}
				<section className="relative min-h-[500px] overflow-hidden py-16 md:py-24">
					{/* Background Image with optimized loading */}
					<div className="absolute inset-0 z-0">
						<div
							className="h-full w-full bg-cover bg-center bg-no-repeat"
							style={{
								backgroundImage: 'url(/assets/hero/hero-bg.png)',
							}}
						/>
						{/* Enhanced gradient overlays for better contrast */}
						<div className="absolute inset-0 bg-gradient-to-br from-stone-900/90 via-stone-900/80 to-stone-800/70" />
						<div className="absolute inset-0 bg-gradient-to-t from-stone-900/60 via-transparent to-stone-900/40" />
					</div>

					{/* Content */}
					<div className="container relative z-10 mx-auto px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							animate={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							className="mx-auto max-w-6xl"
						>
							<div className="grid grid-cols-1 items-center gap-12 lg:grid-cols-2 lg:gap-16">
								{/* Enhanced Profile Image */}
								<motion.div
									initial={{ opacity: 0, scale: 0.9 }}
									animate={{ opacity: 1, scale: 1 }}
									transition={{ duration: 0.8, delay: 0.2, ease: 'easeOut' }}
									className="flex justify-center lg:justify-start"
								>
									<div className="relative">
										{/* Glass-morphism container */}
										<div className="absolute inset-0 rounded-full bg-white/10 backdrop-blur-sm" />
										{/* Main image container */}
										<div className="relative h-64 w-64 overflow-hidden rounded-full bg-gradient-to-br from-stone-200/20 to-stone-300/20 backdrop-blur-sm md:h-72 md:w-72 lg:h-80 lg:w-80">
											<img
												src="/assets/hero/profile.png"
												alt="John Schibelli - Senior Frontend Developer"
												className="h-full w-full object-cover"
											/>
										</div>
										{/* Enhanced floating icon badge */}
										<div className="absolute -bottom-2 -right-2 flex h-16 w-16 items-center justify-center rounded-full bg-gradient-to-br from-stone-900 to-stone-800 shadow-2xl backdrop-blur-sm md:h-18 md:w-18">
											<BracketsIcon className="h-8 w-8 text-white md:h-9 md:w-9" />
										</div>
									</div>
								</motion.div>

								{/* Enhanced Hero Content */}
								<motion.div
									initial={{ opacity: 0, x: 20 }}
									animate={{ opacity: 1, x: 0 }}
									transition={{ duration: 0.8, delay: 0.4, ease: 'easeOut' }}
									className="text-center lg:text-left"
								>
									{/* Business-focused tagline */}
									<motion.div
										initial={{ opacity: 0, y: 10 }}
										animate={{ opacity: 1, y: 0 }}
										transition={{ duration: 0.6, delay: 0.6, ease: 'easeOut' }}
										className="mb-4"
									>
										<p className="text-lg font-medium text-stone-300 md:text-xl">
											Transforming Ideas Into Digital Success
										</p>
									</motion.div>

									{/* Enhanced name with better typography */}
									<motion.h1
										initial={{ opacity: 0, y: 20 }}
										animate={{ opacity: 1, y: 0 }}
										transition={{ duration: 0.8, delay: 0.7, ease: 'easeOut' }}
										className="mb-4 text-4xl font-bold tracking-tight text-white md:text-5xl lg:text-6xl"
									>
										John Schibelli
									</motion.h1>

									{/* Enhanced title */}
									<motion.p
										initial={{ opacity: 0, y: 15 }}
										animate={{ opacity: 1, y: 0 }}
										transition={{ duration: 0.8, delay: 0.8, ease: 'easeOut' }}
										className="mb-6 text-xl font-semibold text-stone-200 md:text-2xl lg:text-3xl"
									>
										Senior Front-End Developer
									</motion.p>

									{/* Enhanced description with business outcomes */}
									<motion.p
										initial={{ opacity: 0, y: 15 }}
										animate={{ opacity: 1, y: 0 }}
										transition={{ duration: 0.8, delay: 0.9, ease: 'easeOut' }}
										className="mb-8 text-base leading-relaxed text-stone-300 md:text-lg lg:text-xl"
									>
										Delivering high-performance web applications that drive business growth. 
										Expert in React, Next.js, and TypeScript with 15+ years of proven results 
										in building scalable digital experiences that exceed client expectations.
									</motion.p>

									{/* Glass-morphism stats cards */}
									<motion.div
										initial={{ opacity: 0, y: 20 }}
										animate={{ opacity: 1, y: 0 }}
										transition={{ duration: 0.8, delay: 1.0, ease: 'easeOut' }}
										className="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-3 lg:justify-start"
									>
										<div className="rounded-lg bg-white/10 p-4 backdrop-blur-sm border border-white/20">
											<div className="flex items-center justify-center gap-2 text-stone-300 lg:justify-start">
												<MapPinIcon className="h-5 w-5" />
												<span className="text-sm font-medium md:text-base">Towaco, NJ</span>
											</div>
										</div>
										<div className="rounded-lg bg-white/10 p-4 backdrop-blur-sm border border-white/20">
											<div className="flex items-center justify-center gap-2 text-stone-300 lg:justify-start">
												<BriefcaseIcon className="h-5 w-5" />
												<span className="text-sm font-medium md:text-base">15+ Years</span>
											</div>
										</div>
										<div className="rounded-lg bg-white/10 p-4 backdrop-blur-sm border border-white/20">
											<div className="flex items-center justify-center gap-2 text-stone-300 lg:justify-start">
												<CalendarIcon className="h-5 w-5" />
												<span className="text-sm font-medium md:text-base">Available</span>
											</div>
										</div>
									</motion.div>

									{/* Enhanced CTA buttons with staggered animation */}
									<motion.div
										initial={{ opacity: 0, y: 20 }}
										animate={{ opacity: 1, y: 0 }}
										transition={{ duration: 0.8, delay: 1.1, ease: 'easeOut' }}
										className="flex flex-col justify-center gap-4 sm:flex-row lg:justify-start"
									>
										<Button
											size="lg"
											className="min-w-[180px] justify-center bg-white/20 backdrop-blur-sm border border-white/30 text-white hover:bg-white/30 hover:border-white/50 transition-all duration-300"
											asChild
										>
											<Link href="/contact">
												Get In Touch
												<ArrowRightIcon className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
											</Link>
										</Button>
										<Button
											size="lg"
											variant="outline"
											className="min-w-[160px] justify-center border-white/30 text-white hover:bg-white/10 hover:border-white/50 transition-all duration-300"
											asChild
										>
											<Link href="/projects">View My Projects</Link>
										</Button>
									</motion.div>
								</motion.div>
							</div>
						</motion.div>
					</div>
				</section>

				{/* Professional Summary */}
				<section className="bg-background py-16">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-4xl text-center"
						>
							<h2 className="mb-4 text-3xl font-bold text-stone-900 md:text-4xl dark:text-stone-100">
								What I Do
							</h2>
							<p className="text-lg leading-relaxed text-stone-600 md:text-xl dark:text-stone-400">
								Senior Front-End Developer with 15+ years of experience building scalable,
								high-performance web apps and company websites. Skilled in React, Next.js,
								TypeScript, and Tailwind CSS with a strong focus on accessibility, SEO, and client
								success. Technical lead behind IntraWeb Technologies&apos; digital presence and
								AI-driven content collaboration tooling (SynaplyAI).
							</p>
						</motion.div>
					</Container>
				</section>

				{/* Resume Accordion Section */}
				<section className="bg-muted py-20">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-4xl"
						>
							<div className="mb-12 text-center">
								<h2 className="mb-4 text-3xl font-bold text-stone-900 md:text-4xl dark:text-stone-100">
									Professional Background
								</h2>
								<p className="text-lg text-stone-600 dark:text-stone-400">
									Explore my experience, skills, and qualifications
								</p>
							</div>

							<Accordion type="single" collapsible className="w-full space-y-4">
								{/* Experience */}
								<AccordionItem
									value="experience"
									className="rounded-lg border border-border bg-card shadow-sm transition-all duration-300 hover:border-border hover:shadow-md"
								>
									<AccordionTrigger className="rounded-t-lg px-6 py-4 text-left transition-colors duration-200">
										<div className="flex items-center gap-3">
											<BriefcaseIcon className="h-5 w-5 text-muted-foreground transition-colors duration-200" />
											<span className="text-lg font-semibold">Professional Experience</span>
										</div>
									</AccordionTrigger>
									<AccordionContent className="px-6">
										<div className="space-y-8">
											{experience.map((job, index) => (
												<div
													key={index}
													className="border-l-4 border-primary/40 pl-6"
												>
													<div className="mb-2 flex flex-col sm:flex-row sm:items-center sm:justify-between">
														<h3 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
															{job.title}
														</h3>
														<div className="mt-1 text-sm text-stone-500 sm:mt-0 dark:text-stone-400">
															{job.period}
														</div>
													</div>
													<div className="mb-3 flex items-center gap-2 text-stone-600 dark:text-stone-400">
														<span className="font-medium">{job.company}</span>
														<span>•</span>
														<span>{job.location}</span>
													</div>
													<p className="mb-4 text-stone-600 dark:text-stone-400">
														{job.description}
													</p>
													<ul className="space-y-2">
														{job.achievements.map((achievement, idx) => (
															<li
																key={idx}
																className="flex items-start gap-2 text-sm text-stone-600 dark:text-stone-400"
															>
																<StarIcon className="mt-1 h-3 w-3 flex-shrink-0 text-stone-400 dark:text-stone-500" />
																{achievement}
															</li>
														))}
													</ul>
												</div>
											))}
										</div>
									</AccordionContent>
								</AccordionItem>

								{/* Skills */}
								<AccordionItem
									value="skills"
									className="rounded-lg border border-border bg-card shadow-sm transition-all duration-300 hover:border-border hover:shadow-md"
								>
									<AccordionTrigger className="rounded-t-lg px-6 py-4 text-left transition-colors duration-200">
										<div className="flex items-center gap-3">
											<LightbulbIcon className="h-5 w-5 text-muted-foreground transition-colors duration-200" />
											<span className="text-lg font-semibold">Skills & Technologies</span>
										</div>
									</AccordionTrigger>
									<AccordionContent className="px-6">
										<div className="grid grid-cols-1 gap-6 md:grid-cols-2">
											{Object.entries(skills).map(([category, skillList]) => (
												<div key={category} className="space-y-3">
													<h4 className="font-semibold text-stone-900 dark:text-stone-100">
														{category}
													</h4>
													<div className="flex flex-wrap gap-2">
														{skillList.map((skill) => (
															<Badge
																key={skill}
																variant="secondary"
															>
																{skill}
															</Badge>
														))}
													</div>
												</div>
											))}
										</div>
									</AccordionContent>
								</AccordionItem>

								{/* Education */}
								<AccordionItem
									value="education"
									className="rounded-lg border border-border bg-card shadow-sm transition-all duration-300 hover:border-border hover:shadow-md"
								>
									<AccordionTrigger className="rounded-t-lg px-6 py-4 text-left transition-colors duration-200">
										<div className="flex items-center gap-3">
											<GraduationCapIcon className="h-5 w-5 text-muted-foreground transition-colors duration-200" />
											<span className="text-lg font-semibold">Education & Certifications</span>
										</div>
									</AccordionTrigger>
									<AccordionContent className="px-6">
										<div className="space-y-6">
											{education.map((edu, index) => (
												<div
													key={index}
													className="border-l-4 border-primary/40 pl-6"
												>
													<div className="mb-2 flex flex-col sm:flex-row sm:items-center sm:justify-between">
														<h4 className="text-lg font-semibold text-stone-900 dark:text-stone-100">
															{edu.degree}
														</h4>
														<div className="mt-1 text-sm text-stone-500 sm:mt-0 dark:text-stone-400">
															{edu.period}
														</div>
													</div>
													<div className="mb-2 flex items-center gap-2 text-stone-600 dark:text-stone-400">
														<span>{edu.school}</span>
														<span>•</span>
														<span>{edu.location}</span>
													</div>
													<p className="text-sm text-stone-600 dark:text-stone-400">
														{edu.description}
													</p>
												</div>
											))}

											<div className="border-t border-stone-200 pt-4 dark:border-stone-600">
												<h4 className="mb-3 font-semibold text-stone-900 dark:text-stone-100">
													Certifications
												</h4>
												<div className="space-y-2">
													{certifications.map((cert, index) => (
														<div key={index} className="flex items-center justify-between">
															<span className="text-stone-600 dark:text-stone-400">
																{cert.name}
															</span>
															<span className="text-sm text-stone-500 dark:text-stone-500">
																{cert.year}
															</span>
														</div>
													))}
												</div>
											</div>
										</div>
									</AccordionContent>
								</AccordionItem>

								{/* Approach */}
								<AccordionItem
									value="approach"
									className="rounded-lg border border-border bg-card shadow-sm transition-all duration-300 hover:border-border hover:shadow-md"
								>
									<AccordionTrigger className="rounded-t-lg px-6 py-4 text-left transition-colors duration-200">
										<div className="flex items-center gap-3">
											<BookOpenIcon className="h-5 w-5 text-muted-foreground transition-colors duration-200" />
											<span className="text-lg font-semibold">My Approach & Philosophy</span>
										</div>
									</AccordionTrigger>
									<AccordionContent className="px-6">
										<div className="space-y-4">
											<div>
												<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
													Development Philosophy
												</h4>
												<p className="text-stone-600 dark:text-stone-400">
													I believe in writing clean, maintainable code and staying up-to-date with
													the latest industry best practices. I&apos;m passionate about AI-driven
													development and finding innovative ways to improve the development
													workflow.
												</p>
											</div>
											<div>
												<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
													Work Style
												</h4>
												<p className="text-stone-600 dark:text-stone-400">
													I thrive in collaborative environments and believe in the power of clear
													communication. I&apos;m committed to delivering high-quality solutions
													that exceed expectations while meeting deadlines.
												</p>
											</div>
											<div>
												<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
													Continuous Learning
												</h4>
												<p className="text-stone-600 dark:text-stone-400">
													When I&apos;m not coding, you&apos;ll find me exploring new technologies,
													contributing to open source projects, or sharing knowledge with the
													developer community.
												</p>
											</div>
										</div>
									</AccordionContent>
								</AccordionItem>
							</Accordion>
						</motion.div>
					</Container>
				</section>

				{/* CTA Section */}
				<section className="bg-background py-20">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-4xl text-center"
						>
							<div className="rounded-lg border border-border bg-accent p-8 shadow-sm">
								<h2 className="mb-4 text-3xl font-bold text-stone-900 dark:text-stone-100">
									Let&apos;s Work Together
								</h2>
								<p className="mb-8 text-lg text-stone-600 dark:text-stone-400">
									I&apos;m available for freelance projects and consulting opportunities. Whether
									you need a complete application built from scratch or help optimizing an existing
									codebase, I&apos;d love to hear about your project.
								</p>
								<div className="flex flex-col justify-center gap-4 sm:flex-row">
									<Button
										size="lg"
										asChild
									>
										<Link href="/contact">
											Start a Project
											<ArrowRightIcon className="ml-2 h-4 w-4" />
										</Link>
									</Button>
									<Button
										size="lg"
										variant="outline"
										asChild
									>
										<Link href="/projects">View My Projects</Link>
									</Button>
								</div>
							</div>
						</motion.div>
					</Container>
				</section>
			</main>

			{/* Footer */}
			<Footer publication={publication} />

			{/* Chatbot */}
			<Chatbot />
		</AppProvider>
	);
}

/**
 * Static props generation for About page with comprehensive error handling
 * @returns Promise with publication data or fallback data
 */
export const getStaticProps: GetStaticProps<Props> = async () => {
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST || 'mindware.hashnode.dev';

	// Validate environment variables
	if (!process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT) {
		console.warn('NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT environment variable is not set');
	}

	try {
		const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			PostsByPublicationDocument,
			{
				first: 0,
				host: host,
			},
		);

		const publication = data.publication;
		if (!publication) {
			console.error('No publication data found for host:', host);
			return {
				notFound: true,
			};
		}

		// Validate publication data structure
		if (!publication.title && !publication.displayTitle) {
			console.warn('Publication missing title and displayTitle');
		}

		return {
			props: {
				publication,
			},
			revalidate: 1,
		};
	} catch (error) {
		console.error('Error fetching publication data for About page:', error);
		
		// Enhanced fallback response with better error handling
		const fallbackPublication = {
			id: 'fallback-about',
			title: 'John Schibelli',
			displayTitle: 'John Schibelli',
			descriptionSEO: 'Senior Front-End Developer with 15+ years of experience building scalable, high-performance web applications.',
			url: 'https://johnschibelli.com',
			posts: {
				totalDocuments: 0,
			},
			preferences: {
				logo: null,
			},
			author: {
				name: 'John Schibelli',
				profilePicture: null,
			},
			followersCount: 0,
			isTeam: false,
			favicon: null,
			ogMetaData: {
				image: null,
			},
		};

		return {
			props: {
				publication: fallbackPublication as any,
			},
			revalidate: 1,
		};
	}
};
