/* eslint-disable @next/next/no-img-element */
import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import { motion } from 'framer-motion';
import request from 'graphql-request';
import {
	ArrowRightIcon,
	BookOpenIcon,
	BracketsIcon,
	BriefcaseIcon,
	CalendarIcon,
	GraduationCapIcon,
	MapPinIcon,
	StarIcon,
	MailIcon,
	LinkedinIcon,
	ClockIcon,
	UsersIcon,
	BuildingIcon,
	CodeIcon,
} from 'lucide-react';
import { GetStaticProps } from 'next';
import Link from 'next/link';
import { AppProvider } from '../components/contexts/appContext';
import Chatbot from '../components/features/chatbot/Chatbot';
import ModernHeader from '../components/features/navigation/modern-header';
import VisualSkillsShowcase from '../components/features/about/visual-skills-showcase';
import { Container } from '../components/shared/container';
import { Footer } from '../components/shared/footer';
import { SEOHead } from '../components/shared/seo-head';
import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from '../components/ui/accordion';
import { Button } from '../components/ui';
import { generatePersonStructuredData } from '../lib/structured-data';
import {
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT || 'https://gql.hashnode.com/';

type Props = {
	publication: PublicationFragment;
};

/**
 * About page component displaying professional information and experience
 * @param publication - Publication data from Hashnode
 * @returns JSX element for the about page
 */
export default function About({ publication }: Props) {

	const experience = [
		{
			title: 'Senior Front-End Developer',
			company: 'IntraWeb Technology',
			period: '2020 - Present',
			location: 'Montville, NJ',
			description: 'Lead front-end for company site and client projects; incubated SynaplyAI.',
			achievements: [
				'Built the IntraWeb Technologies website with Next.js, React, TypeScript, and Tailwind CSS; shipped an accessible, SEO-optimized presence.',
				'Delivered custom WordPress and Shopify builds emphasizing mobile performance and SEO for clients including KAL Design.',
				'Scoped requirements, owned timelines, and served as primary client liaison to ensure quality delivery and satisfaction.',
				'Incubated SynaplyAI (multi-tenant AI content collaboration) with front-end architecture, OpenAI integrations, real-time collab editing, and adaptive AI content generation.',
			],
		},
		{
			title: 'Full-Stack Developer',
			company: 'ColorStreet',
			period: '2024',
			location: 'Totowa, NJ',
			description: 'Contributed to e-commerce platform quality and integrations.',
			achievements: [
				'Implemented automated UI testing with Playwright, improving reliability across releases.',
				'Integrated and validated Nest.js APIs; ensured stable data flow and interface alignment.',
				'Partnered with QA, design, and product to support sprint delivery and UI improvements.',
			],
		},
		{
			title: 'Senior Front-End Developer',
			company: 'Executive Five Star',
			period: '2016 - 2020',
			location: 'Montville, NJ',
			description: "Owned front-end for the company's car service site and online booking.",
			achievements: [
				'Developed and maintained the primary WordPress site with improved usability and mobile responsiveness.',
				'Integrated Limo Anywhere API for real-time reservations and back-office sync.',
				'Streamlined dispatch workflows by connecting booking front-end to internal systems.',
			],
		},
		{
			title: 'Front-End Developer',
			company: 'Robert Half Technology',
			period: '2013 - 2016',
			location: 'Parsippany, NJ',
			description: 'Built enterprise UIs and internal tooling in JavaScript ecosystems.',
			achievements: [
				'Developed UIs for internal financial platforms using JavaScript, jQuery, and Bootstrap to improve reporting workflows.',
				'Built interactive presentation tools for pharmaceutical clients using Veeva CRM and HTML5.',
				'Delivered front-end features aligned with enterprise UX guidelines in Agile cycles.',
				'Led multiple internal WordPress projects and mentored junior developers on front-end best practices.',
			],
		},
		{
			title: 'Web Developer (Contract)',
			company: 'Level-Nine Creative',
			period: '2009 - 2013',
			location: 'Merritt Island, FL',
			description: 'Delivered custom WordPress sites for small businesses and agencies.',
			achievements: [
				'Designed and developed custom websites using WordPress, PHP, JavaScript, and CSS.',
				'Built reusable UI components for responsive, cross-browser performance.',
				'Customized themes/plugins to support marketing workflows and SEO.',
			],
		},
		{
			title: 'Web Development Program Director',
			company: 'Anthem Institute',
			period: '2005 - 2009',
			location: 'Parsippany, NJ',
			description: 'Led curriculum and instruction across multiple campuses.',
			achievements: [
				'Taught HTML, CSS, JavaScript, PHP, and MySQL; built industry-ready skills.',
				'Managed a team of 8 instructors across 4 campuses; ensured curriculum alignment.',
				'Oversaw accreditation compliance; partnered with Pearson VUE for certification programs.',
			],
		},
	];

	const education = [
		{
			degree: 'Web & Graphic Design',
			school: 'The Chubb Institute',
			period: '2004',
			location: 'New Jersey',
			description: 'Diploma in Web & Graphic Design',
		},
	];

	const certifications = [
		{
			name: '15+ Years Experience',
			issuer: 'Web Development',
			year: '2005-2025',
		},
	];

	return (
		<AppProvider publication={publication}>
			<SEOHead
				title={`About - ${publication.displayTitle || publication.title}`}
				description="Learn more about John Schibelli, Senior Front-End Developer specializing in React, Next.js, TypeScript, and AI-driven development."
				keywords={[
					'John Schibelli',
					'Front-End Developer',
					'React Developer',
					'Next.js Developer',
					'TypeScript Developer',
					'Web Development',
					'Professional Experience',
					'Skills',
					'Portfolio',
				]}
				canonical="/about"
				ogImage={getAutogeneratedPublicationOG(publication)}
				ogType="profile"
				structuredData={generatePersonStructuredData({
					name: 'John Schibelli',
					description: 'Senior Front-End Developer with 15+ years of experience building scalable, high-performance web applications.',
					url: 'https://johnschibelli.com',
					jobTitle: 'Senior Front-End Developer',
					knowsAbout: [
						'JavaScript (ES6+)',
						'TypeScript',
						'React',
						'Next.js',
						'Node.js',
						'HTML5',
						'CSS3',
						'Tailwind CSS',
						'GraphQL',
						'REST APIs',
						'Web Accessibility',
						'SEO Optimization',
						'Performance Optimization',
						'UI/UX Design',
						'Testing',
						'DevOps',
						'Cloud Computing',
					],
					alumniOf: [
						{
							name: 'The Chubb Institute',
						},
					],
					hasCredential: [
						{
							name: '15+ Years Experience',
							credentialCategory: 'Work Experience',
							recognizedBy: {
								name: 'Web Development Industry',
							},
						},
					],
					sameAs: [
						'https://linkedin.com/in/johnschibelli',
						'https://github.com/johnschibelli',
						'https://twitter.com/johnschibelli',
					],
				})}
			/>

			<ModernHeader publication={publication} />

			<main className="min-h-screen bg-background">
				{/* Hero Section */}
				<section
					className="relative min-h-[400px] overflow-hidden bg-muted py-12 md:py-16"
					style={{
						backgroundImage: 'url(/assets/hero/hero-bg.png)',
						backgroundSize: 'cover',
						backgroundPosition: 'center',
						backgroundRepeat: 'no-repeat',
					}}
				>
					{/* Background Overlay */}
					<div className="absolute inset-0 z-0 bg-muted/70"></div>
					{/* Content Overlay */}
					<div className="relative z-10">
						<Container className="px-4">
							<motion.div
								initial={{ opacity: 0, y: 20 }}
								animate={{ opacity: 1, y: 0 }}
								transition={{ duration: 0.8, ease: 'easeOut' }}
								className="mx-auto max-w-5xl"
							>
								<div className="grid grid-cols-1 items-center gap-8 lg:grid-cols-3 lg:gap-10">
									{/* Profile Image */}
									<div className="flex justify-center lg:col-span-1">
										<div className="relative">
											<div className="h-48 w-48 overflow-hidden rounded-full bg-gradient-to-br from-stone-200 to-stone-300 md:h-56 md:w-56 lg:h-52 lg:w-52 dark:from-stone-700 dark:to-stone-600">
												<img
													src="/assets/hero/profile.png"
													alt="John Schibelli - Senior Frontend Developer"
													className="h-full w-full object-cover"
												/>
											</div>
											<div className="absolute -bottom-1 -right-1 flex h-12 w-12 items-center justify-center rounded-full bg-stone-900 md:h-14 md:w-14 dark:bg-stone-100">
												<BracketsIcon className="h-6 w-6 text-white md:h-7 md:w-7 dark:text-stone-900" />
											</div>
										</div>
									</div>

									{/* Hero Content */}
									<div className="text-center lg:col-span-2 lg:text-left">
										<h1 className="mb-4 text-4xl font-bold text-stone-900 md:text-5xl lg:text-6xl dark:text-stone-100">
											John Schibelli
										</h1>
										<p className="mb-4 text-xl text-stone-600 md:text-2xl lg:text-3xl dark:text-stone-400">
											Senior Front-End Developer
										</p>
										<p className="mb-6 text-base leading-relaxed text-stone-600 md:text-lg dark:text-stone-400">
											Senior Front-End Developer with 15+ years of experience building scalable,
											high-performance web apps and company websites. Skilled in React, Next.js,
											TypeScript, and Tailwind CSS with a strong focus on accessibility, SEO, and
											client success.
										</p>

										<div className="mb-6 flex flex-wrap justify-center gap-3 text-sm text-stone-500 md:gap-4 lg:justify-start dark:text-stone-400">
											<div className="flex items-center gap-2">
												<MapPinIcon className="h-4 w-4" />
												<span>Towaco, NJ</span>
											</div>
											<div className="flex items-center gap-2">
												<BriefcaseIcon className="h-4 w-4" />
												<span>15+ Years Experience</span>
											</div>
											<div className="flex items-center gap-2">
												<CalendarIcon className="h-4 w-4" />
												<span>Available for Projects</span>
											</div>
										</div>

										<div className="flex flex-col justify-center gap-3 sm:flex-row lg:justify-start">
											<Button
												size="lg"
												asChild
											>
												<Link href="/contact">
													Get In Touch
													<ArrowRightIcon className="ml-2 h-4 w-4" />
												</Link>
											</Button>
											<Button
												size="lg"
												variant="outline"
												asChild
											>
												<Link href="/projects">View My Projects</Link>
											</Button>
										</div>
									</div>
								</div>
							</motion.div>
						</Container>
					</div>
				</section>

				{/* Professional Summary */}
				<section className="bg-background py-16">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-4xl text-center"
						>
							<h2 className="mb-4 text-3xl font-bold text-stone-900 md:text-4xl dark:text-stone-100">
								What I Do
							</h2>
							<p className="text-lg leading-relaxed text-stone-600 md:text-xl dark:text-stone-400">
								Senior Front-End Developer with 15+ years of experience building scalable,
								high-performance web apps and company websites. Skilled in React, Next.js,
								TypeScript, and Tailwind CSS with a strong focus on accessibility, SEO, and client
								success. Technical lead behind IntraWeb Technologies&apos; digital presence and
								AI-driven content collaboration tooling (SynaplyAI).
							</p>
						</motion.div>
					</Container>
				</section>

				{/* Resume Accordion Section */}
				<section className="bg-muted py-20">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-4xl"
						>
							<div className="mb-12 text-center">
								<h2 className="mb-4 text-3xl font-bold text-stone-900 md:text-4xl dark:text-stone-100">
									Professional Background
								</h2>
								<p className="text-lg text-stone-600 dark:text-stone-400">
									Explore my experience, skills, and qualifications
								</p>
							</div>

							<Accordion type="single" collapsible className="w-full space-y-4">
								{/* Experience */}
								<AccordionItem
									value="experience"
									className="rounded-lg border border-border bg-card shadow-sm transition-all duration-300 hover:border-border hover:shadow-md"
								>
									<AccordionTrigger className="rounded-t-lg px-6 py-4 text-left transition-colors duration-200">
										<div className="flex items-center gap-3">
											<BriefcaseIcon className="h-5 w-5 text-muted-foreground transition-colors duration-200" />
											<span className="text-lg font-semibold">Professional Experience</span>
										</div>
									</AccordionTrigger>
									<AccordionContent className="px-6">
										<div className="space-y-8">
											{experience.map((job, index) => (
												<div
													key={index}
													className="border-l-4 border-primary/40 pl-6"
												>
													<div className="mb-2 flex flex-col sm:flex-row sm:items-center sm:justify-between">
														<h3 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
															{job.title}
														</h3>
														<div className="mt-1 text-sm text-stone-500 sm:mt-0 dark:text-stone-400">
															{job.period}
														</div>
													</div>
													<div className="mb-3 flex items-center gap-2 text-stone-600 dark:text-stone-400">
														<span className="font-medium">{job.company}</span>
														<span>•</span>
														<span>{job.location}</span>
													</div>
													<p className="mb-4 text-stone-600 dark:text-stone-400">
														{job.description}
													</p>
													<ul className="space-y-2">
														{job.achievements.map((achievement, idx) => (
															<li
																key={idx}
																className="flex items-start gap-2 text-sm text-stone-600 dark:text-stone-400"
															>
																<StarIcon className="mt-1 h-3 w-3 flex-shrink-0 text-stone-400 dark:text-stone-500" />
																{achievement}
															</li>
														))}
													</ul>
												</div>
											))}
										</div>
									</AccordionContent>
								</AccordionItem>

								{/* Skills */}
								<AccordionItem
									value="skills"
									className="rounded-lg border border-border bg-card shadow-sm transition-all duration-300 hover:border-border hover:shadow-md"
								>
									<AccordionTrigger className="rounded-t-lg px-6 py-4 text-left transition-colors duration-200">
										<div className="flex items-center gap-3">
											<BookOpenIcon className="h-5 w-5 text-muted-foreground transition-colors duration-200" />
											<span className="text-lg font-semibold">Skills & Technologies</span>
										</div>
									</AccordionTrigger>
									<AccordionContent className="px-6">
										<VisualSkillsShowcase />
									</AccordionContent>
								</AccordionItem>

								{/* Education */}
								<AccordionItem
									value="education"
									className="rounded-lg border border-border bg-card shadow-sm transition-all duration-300 hover:border-border hover:shadow-md"
								>
									<AccordionTrigger className="rounded-t-lg px-6 py-4 text-left transition-colors duration-200">
										<div className="flex items-center gap-3">
											<GraduationCapIcon className="h-5 w-5 text-muted-foreground transition-colors duration-200" />
											<span className="text-lg font-semibold">Education & Certifications</span>
										</div>
									</AccordionTrigger>
									<AccordionContent className="px-6">
										<div className="space-y-6">
											{education.map((edu, index) => (
												<div
													key={index}
													className="border-l-4 border-primary/40 pl-6"
												>
													<div className="mb-2 flex flex-col sm:flex-row sm:items-center sm:justify-between">
														<h4 className="text-lg font-semibold text-stone-900 dark:text-stone-100">
															{edu.degree}
														</h4>
														<div className="mt-1 text-sm text-stone-500 sm:mt-0 dark:text-stone-400">
															{edu.period}
														</div>
													</div>
													<div className="mb-2 flex items-center gap-2 text-stone-600 dark:text-stone-400">
														<span>{edu.school}</span>
														<span>•</span>
														<span>{edu.location}</span>
													</div>
													<p className="text-sm text-stone-600 dark:text-stone-400">
														{edu.description}
													</p>
												</div>
											))}

											<div className="border-t border-stone-200 pt-4 dark:border-stone-600">
												<h4 className="mb-3 font-semibold text-stone-900 dark:text-stone-100">
													Certifications
												</h4>
												<div className="space-y-2">
													{certifications.map((cert, index) => (
														<div key={index} className="flex items-center justify-between">
															<span className="text-stone-600 dark:text-stone-400">
																{cert.name}
															</span>
															<span className="text-sm text-stone-500 dark:text-stone-500">
																{cert.year}
															</span>
														</div>
													))}
												</div>
											</div>
										</div>
									</AccordionContent>
								</AccordionItem>

								{/* Approach */}
								<AccordionItem
									value="approach"
									className="rounded-lg border border-border bg-card shadow-sm transition-all duration-300 hover:border-border hover:shadow-md"
								>
									<AccordionTrigger className="rounded-t-lg px-6 py-4 text-left transition-colors duration-200">
										<div className="flex items-center gap-3">
											<BookOpenIcon className="h-5 w-5 text-muted-foreground transition-colors duration-200" />
											<span className="text-lg font-semibold">My Approach & Philosophy</span>
										</div>
									</AccordionTrigger>
									<AccordionContent className="px-6">
										<div className="space-y-4">
											<div>
												<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
													Development Philosophy
												</h4>
												<p className="text-stone-600 dark:text-stone-400">
													I believe in writing clean, maintainable code and staying up-to-date with
													the latest industry best practices. I&apos;m passionate about AI-driven
													development and finding innovative ways to improve the development
													workflow.
												</p>
											</div>
											<div>
												<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
													Work Style
												</h4>
												<p className="text-stone-600 dark:text-stone-400">
													I thrive in collaborative environments and believe in the power of clear
													communication. I&apos;m committed to delivering high-quality solutions
													that exceed expectations while meeting deadlines.
												</p>
											</div>
											<div>
												<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
													Continuous Learning
												</h4>
												<p className="text-stone-600 dark:text-stone-400">
													When I&apos;m not coding, you&apos;ll find me exploring new technologies,
													contributing to open source projects, or sharing knowledge with the
													developer community.
												</p>
											</div>
										</div>
									</AccordionContent>
								</AccordionItem>
							</Accordion>
						</motion.div>
					</Container>
				</section>

				{/* Enhanced Contact Section */}
				<section className="bg-background py-20">
					<Container className="px-4">
						<motion.div
							initial={{ opacity: 0, y: 20 }}
							whileInView={{ opacity: 1, y: 0 }}
							transition={{ duration: 0.8, ease: 'easeOut' }}
							viewport={{ once: true }}
							className="mx-auto max-w-6xl"
						>
							{/* Header */}
							<div className="mb-12 text-center">
								<h2 className="mb-4 text-3xl font-bold text-stone-900 md:text-4xl dark:text-stone-100">
									Let&apos;s Connect & Collaborate
								</h2>
								<p className="text-lg text-stone-600 dark:text-stone-400">
									Ready to bring your ideas to life? I&apos;m here to help you succeed.
								</p>
							</div>

							{/* Primary CTAs */}
							<div className="mb-12 grid gap-6 md:grid-cols-2">
								{/* Start Your Project */}
								<div className="rounded-lg border border-border bg-card p-8 shadow-sm transition-all duration-300 hover:shadow-md">
									<div className="mb-4 flex items-center gap-3">
										<div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
											<CodeIcon className="h-6 w-6 text-primary" />
										</div>
										<h3 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
											Start Your Project
										</h3>
									</div>
									<p className="mb-6 text-stone-600 dark:text-stone-400">
										Ready to build something amazing? Let&apos;s discuss your project requirements and bring your vision to life.
									</p>
									<Button size="lg" className="w-full" asChild>
										<Link href="/contact">
											Get Started Today
											<ArrowRightIcon className="ml-2 h-4 w-4" />
										</Link>
									</Button>
								</div>

								{/* View Portfolio */}
								<div className="rounded-lg border border-border bg-card p-8 shadow-sm transition-all duration-300 hover:shadow-md">
									<div className="mb-4 flex items-center gap-3">
										<div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
											<BriefcaseIcon className="h-6 w-6 text-primary" />
										</div>
										<h3 className="text-xl font-semibold text-stone-900 dark:text-stone-100">
											View My Work
										</h3>
									</div>
									<p className="mb-6 text-stone-600 dark:text-stone-400">
										Explore my portfolio of projects and see the quality of work I deliver for clients.
									</p>
									<Button size="lg" variant="outline" className="w-full" asChild>
										<Link href="/projects">
											View Portfolio
											<ArrowRightIcon className="ml-2 h-4 w-4" />
										</Link>
									</Button>
								</div>
							</div>

							{/* Audience-Specific CTAs */}
							<div className="mb-12">
								<h3 className="mb-6 text-center text-2xl font-semibold text-stone-900 dark:text-stone-100">
									I Work With
								</h3>
								<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
									{/* Recruiters */}
									<div className="rounded-lg border border-border bg-card p-6 text-center transition-all duration-300 hover:border-primary/50 hover:shadow-sm">
										<div className="mb-3 flex justify-center">
											<div className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900/30">
												<UsersIcon className="h-5 w-5 text-blue-600 dark:text-blue-400" />
											</div>
										</div>
										<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
											Recruiters
										</h4>
										<p className="text-sm text-stone-600 dark:text-stone-400">
											Open to new opportunities and exciting roles
										</p>
									</div>

									{/* Startup Founders */}
									<div className="rounded-lg border border-border bg-card p-6 text-center transition-all duration-300 hover:border-primary/50 hover:shadow-sm">
										<div className="mb-3 flex justify-center">
											<div className="flex h-10 w-10 items-center justify-center rounded-full bg-green-100 dark:bg-green-900/30">
												<StarIcon className="h-5 w-5 text-green-600 dark:text-green-400" />
											</div>
										</div>
										<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
											Startup Founders
										</h4>
										<p className="text-sm text-stone-600 dark:text-stone-400">
											MVP development and technical consulting
										</p>
									</div>

									{/* Enterprise */}
									<div className="rounded-lg border border-border bg-card p-6 text-center transition-all duration-300 hover:border-primary/50 hover:shadow-sm">
										<div className="mb-3 flex justify-center">
											<div className="flex h-10 w-10 items-center justify-center rounded-full bg-purple-100 dark:bg-purple-900/30">
												<BuildingIcon className="h-5 w-5 text-purple-600 dark:text-purple-400" />
											</div>
										</div>
										<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
											Enterprise
										</h4>
										<p className="text-sm text-stone-600 dark:text-stone-400">
											Technical consulting and architecture
										</p>
									</div>

									{/* Fellow Developers */}
									<div className="rounded-lg border border-border bg-card p-6 text-center transition-all duration-300 hover:border-primary/50 hover:shadow-sm">
										<div className="mb-3 flex justify-center">
											<div className="flex h-10 w-10 items-center justify-center rounded-full bg-orange-100 dark:bg-orange-900/30">
												<CodeIcon className="h-5 w-5 text-orange-600 dark:text-orange-400" />
											</div>
										</div>
										<h4 className="mb-2 font-semibold text-stone-900 dark:text-stone-100">
											Developers
										</h4>
										<p className="text-sm text-stone-600 dark:text-stone-400">
											Collaboration and knowledge sharing
										</p>
									</div>
								</div>
							</div>

							{/* Contact Information & Social Links */}
							<div className="rounded-lg border border-border bg-accent p-8">
								<div className="grid gap-8 md:grid-cols-2">
									{/* Contact Info */}
									<div>
										<h3 className="mb-4 text-xl font-semibold text-stone-900 dark:text-stone-100">
											Get In Touch
										</h3>
										<div className="space-y-4">
											<div className="flex items-center gap-3">
												<MailIcon className="h-5 w-5 text-stone-500 dark:text-stone-400" />
												<div>
													<p className="font-medium text-stone-900 dark:text-stone-100">
														Email
													</p>
													<a 
														href="mailto:john@johnschibelli.com" 
														className="text-stone-600 hover:text-primary dark:text-stone-400 dark:hover:text-primary"
													>
														john@johnschibelli.com
													</a>
												</div>
											</div>
											<div className="flex items-center gap-3">
												<MapPinIcon className="h-5 w-5 text-stone-500 dark:text-stone-400" />
												<div>
													<p className="font-medium text-stone-900 dark:text-stone-100">
														Location
													</p>
													<p className="text-stone-600 dark:text-stone-400">
														Towaco, NJ (Remote Available)
													</p>
												</div>
											</div>
											<div className="flex items-center gap-3">
												<ClockIcon className="h-5 w-5 text-stone-500 dark:text-stone-400" />
												<div>
													<p className="font-medium text-stone-900 dark:text-stone-100">
														Response Time
													</p>
													<p className="text-stone-600 dark:text-stone-400">
														Within 24 hours
													</p>
												</div>
											</div>
										</div>
									</div>

									{/* Social Links & Availability */}
									<div>
										<h3 className="mb-4 text-xl font-semibold text-stone-900 dark:text-stone-100">
											Connect & Availability
										</h3>
										<div className="space-y-4">
											<div className="flex items-center gap-3">
												<LinkedinIcon className="h-5 w-5 text-stone-500 dark:text-stone-400" />
												<div>
													<p className="font-medium text-stone-900 dark:text-stone-100">
														LinkedIn
													</p>
													<a 
														href="https://linkedin.com/in/johnschibelli" 
														target="_blank" 
														rel="noopener noreferrer"
														className="text-stone-600 hover:text-primary dark:text-stone-400 dark:hover:text-primary"
													>
														Connect with me
													</a>
												</div>
											</div>
											<div className="flex items-center gap-3">
												<CalendarIcon className="h-5 w-5 text-stone-500 dark:text-stone-400" />
												<div>
													<p className="font-medium text-stone-900 dark:text-stone-100">
														Availability
													</p>
													<p className="text-stone-600 dark:text-stone-400">
														Available for new projects
													</p>
												</div>
											</div>
											<div className="flex items-center gap-3">
												<StarIcon className="h-5 w-5 text-stone-500 dark:text-stone-400" />
												<div>
													<p className="font-medium text-stone-900 dark:text-stone-100">
														Specialties
													</p>
													<p className="text-stone-600 dark:text-stone-400">
														React, Next.js, TypeScript, AI Integration
													</p>
												</div>
											</div>
										</div>
									</div>
								</div>

								{/* Tertiary CTA */}
								<div className="mt-8 border-t border-border pt-6">
									<div className="flex flex-col items-center justify-between gap-4 sm:flex-row">
										<div className="text-center sm:text-left">
											<h4 className="font-semibold text-stone-900 dark:text-stone-100">
												Ready to start your project?
											</h4>
											<p className="text-sm text-stone-600 dark:text-stone-400">
												Let&apos;s discuss your requirements and create something amazing together.
											</p>
										</div>
										<Button size="lg" asChild>
											<Link href="/contact">
												Start Your Project
												<ArrowRightIcon className="ml-2 h-4 w-4" />
											</Link>
										</Button>
									</div>
								</div>
							</div>
						</motion.div>
					</Container>
				</section>
			</main>

			{/* Footer */}
			<Footer publication={publication} />

			{/* Chatbot */}
			<Chatbot />
		</AppProvider>
	);
}

/**
 * Static props generation for About page with comprehensive error handling
 * @returns Promise with publication data or fallback data
 */
export const getStaticProps: GetStaticProps<Props> = async () => {
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST || 'mindware.hashnode.dev';

	// Validate environment variables
	if (!process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT) {
		console.warn('NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT environment variable is not set');
	}

	try {
		const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			PostsByPublicationDocument,
			{
				first: 0,
				host: host,
			},
		);

		const publication = data.publication;
		if (!publication) {
			console.error('No publication data found for host:', host);
			return {
				notFound: true,
			};
		}

		// Validate publication data structure
		if (!publication.title && !publication.displayTitle) {
			console.warn('Publication missing title and displayTitle');
		}

		return {
			props: {
				publication,
			},
			revalidate: 1,
		};
	} catch (error) {
		console.error('Error fetching publication data for About page:', error);
		
		// Enhanced fallback response with better error handling
		const fallbackPublication = {
			id: 'fallback-about',
			title: 'John Schibelli',
			displayTitle: 'John Schibelli',
			descriptionSEO: 'Senior Front-End Developer with 15+ years of experience building scalable, high-performance web applications.',
			url: 'https://johnschibelli.com',
			posts: {
				totalDocuments: 0,
			},
			preferences: {
				logo: null,
			},
			author: {
				name: 'John Schibelli',
				profilePicture: null,
			},
			followersCount: 0,
			isTeam: false,
			favicon: null,
			ogMetaData: {
				image: null,
			},
		};

		return {
			props: {
				publication: fallbackPublication as any,
			},
			revalidate: 1,
		};
	}
};
