import {
  LuAlignJustify,
  LuArrowUpRight,
  LuLayers,
  LuMessageCircle,
  LuTrendingUp,
  LuCalendar,
  LuBriefcase,
  LuServer,
  LuCode,
  LuDollarSign,
  LuActivity,
  LuZap,
  LuShieldCheck,
  LuFileText,
  LuTimer,
  LuBox,
  LuType,
  LuDatabase,
  LuPackage,
  LuGlobe,
  LuCpu,
  LuRocket,
  LuUsers,
  LuTerminal,
  LuBug,
} from "react-icons/lu"

export const iconMap = {
  alignJustify: LuAlignJustify,
  arrowUpRight: LuArrowUpRight,
  layers: LuLayers,
  "message-circle": LuMessageCircle,
  "trending-up": LuTrendingUp,
  calendar: LuCalendar,
  briefcase: LuBriefcase,
  server: LuServer,
  code: LuCode,
  "dollar-sign": LuDollarSign,
  activity: LuActivity,
  zap: LuZap,
  "shield-check": LuShieldCheck,
  "file-text": LuFileText,
  "check-circle": LuShieldCheck,
  timer: LuTimer,
  box: LuBox,
  type: LuType,
  database: LuDatabase,
  package: LuPackage,
  globe: LuGlobe,
  cpu: LuCpu,
  edit: LuCode,
  image: LuBox,
  search: LuGlobe,
  "bar-chart": LuActivity,
  "x-circle": LuTimer,
  "alert-triangle": LuTimer,
  tag: LuBox,
  folder: LuBox,
  layout: LuLayers,
  "alert-circle": LuTimer,
  "book-open": LuFileText,
  settings: LuServer,
  shield: LuShieldCheck,
  key: LuShieldCheck,
  lock: LuShieldCheck,
  clock: LuTimer,
  archive: LuBox,
  "git-branch": LuCode,
  "rotate-ccw": LuActivity,
  mail: LuMessageCircle,
  cloud: LuGlobe,
  save: LuDatabase,
  "git-pull-request": LuCode,
  tool: LuServer,
  rocket: LuRocket,
  users: LuUsers,
  terminal: LuTerminal,
  api: LuServer, // Using server icon for API
  bug: LuBug,
}
