import {
  LuAlignJustify,
  LuArrowUpRight,
  LuLayers,
  LuMessageCircle,
  LuTrendingUp,
  LuCalendar,
  LuBriefcase,
  LuServer,
  LuCode,
  LuDollarSign,
  LuActivity,
  LuZap,
  LuShieldCheck,
  LuFileText,
  LuCheckCircle2,
  LuTimer,
  LuBox,
  LuType,
  LuDatabase,
  LuPackage,
  LuGlobe,
  LuCpu,
} from "react-icons/lu"

export const iconMap = {
  alignJustify: LuAlignJustify,
  arrowUpRight: LuArrowUpRight,
  layers: LuLayers,
  "message-circle": LuMessageCircle,
  "trending-up": LuTrendingUp,
  calendar: LuCalendar,
  briefcase: LuBriefcase,
  server: LuServer,
  code: LuCode,
  "dollar-sign": LuDollarSign,
  activity: LuActivity,
  zap: LuZap,
  "shield-check": LuShieldCheck,
  "file-text": LuFileText,
  "check-circle": LuCheckCircle2,
  timer: LuTimer,
  box: LuBox,
  type: LuType,
  database: LuDatabase,
  package: LuPackage,
  globe: LuGlobe,
  cpu: LuCpu,
}
