name: PR Base Guard

on:
  pull_request_target:
    types: [opened, reopened, edited]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  enforce-develop-base:
    runs-on: ubuntu-latest
    env:
      FROM_BASE: 'main'
      TO_BASE: 'develop'
    steps:
      - name: Retarget PRs from main to develop
        uses: actions/github-script@v7
        with:
          script: |
            async function run() {
              const pr = context.payload.pull_request;
              if (!pr) { core.notice('No pull_request payload; skipping.'); return; }
              const fromBase = process.env.FROM_BASE || 'main';
              const toBase = process.env.TO_BASE || 'develop';
              const currentBase = pr.base.ref;
              core.info(`PR #${pr.number} current base: ${currentBase}; policy: ${fromBase} -> ${toBase}`);
              if (currentBase === fromBase) {
                try {
                  await github.rest.pulls.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    base: toBase
                  });
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    body: `Base branch was \`${fromBase}\`. Automatically retargeted this PR to \`${toBase}\`.`
                  });
                  core.info('Successfully retargeted PR base.');
                } catch (error) {
                  core.error(`Failed to retarget PR base: ${error.message}`);
                  throw error;
                }
              } else {
                core.info('No retarget needed.');
              }
            }
            run();


