name: PR Base Guard

on:
  pull_request_target:
    types: [opened, reopened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  enforce-develop-base:
    runs-on: ubuntu-latest
    steps:
      - name: Retarget PRs from main to develop
        uses: actions/github-script@v7
        with:
          script: |
            async function run() {
              const pr = context.payload.pull_request;
              if (!pr) return;
              const currentBase = pr.base.ref;
              if (currentBase === 'main') {
                await github.rest.pulls.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  base: 'develop'
                });
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  body: 'Base branch was `main`. Automatically retargeted this PR to `develop`.'
                });
              }
            }
            run();


